### ISSUE TITLE
Touchscreen Scrolling problem

### ISSUE THREAD

**Issue by brbaker92** [Elecrow-keen/Elecrow-LCD101#1]
Instead of scrolling in chromium on RPi it functions like a select.

**Comment by Elecrow-keen** [comment]
Hi,
After checking the issue we can confirm that the issue comes when there is no available scroll function on the screen.
for example: if you go into Chromium browser and enter the default Google page, the page is short on size so it doesn't have scrolling functionality, therefore if you try to scroll it will activate selection action instead.
but, if you search something on google, the scrolling option will show up on the right, which will allow you to use your finger to scroll up and down.
Hope that helps,
~ Keen
